# Generated by Django 4.2.5 on 2024-11-06 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrainte',
            fields=[
                ('id_contrainte', models.AutoField(primary_key=True, serialize=False)),
                ('nom_contrainte', models.CharField(choices=[('enceinte', 'Enceinte'), ('congé', 'Congé'), ('congé de maladie', 'Congé de maladie'), ('état de santé', 'État de santé')], max_length=255)),
                ('type_contrainte', models.CharField(max_length=255)),
                ('date_debut_contrainte', models.DateTimeField()),
                ('date_fin_contrainte', models.DateTimeField()),
                ('status_contrainte', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
