# Generated by Django 4.2.5 on 2024-11-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('NbEtudiantClasse', models.IntegerField()),
                ('libelleClasse', models.CharField(max_length=255)),
                ('id_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niveau.niveau')),
            ],
        ),
    ]
