# Generated by Django 4.2.5 on 2024-11-06 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Salle', '0001_initial'),
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle_examen',
            fields=[
                ('idSE', models.AutoField(primary_key=True, serialize=False)),
                ('date_salle', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.examen')),
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salle.salle')),
            ],
        ),
    ]
