# Generated by Django 4.2.5 on 2024-11-06 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Salle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id_surveillance', models.AutoField(primary_key=True, serialize=False)),
                ('date_surveillance', models.DateTimeField()),
                ('id_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salle.salle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
