# Generated by Django 4.2.5 on 2024-11-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Module', '0001_initial'),
        ('Niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modniv',
            fields=[
                ('idmn', models.AutoField(primary_key=True, serialize=False)),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modniv_modules', to='Module.module')),
                ('id_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modniv_niveaux', to='Niveau.niveau')),
            ],
        ),
    ]
