# Generated by Django 4.2.5 on 2024-11-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('nom_module', models.CharField(max_length=255)),
                ('duree_module', models.IntegerField()),
            ],
        ),
    ]
