# Generated by Django 4.2.5 on 2024-11-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id_niveau', models.AutoField(primary_key=True, serialize=False)),
                ('libelleNiv', models.CharField(max_length=255)),
                ('nbclasseNiv', models.IntegerField()),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
