# Generated by Django 4.2.5 on 2024-11-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('nom_session', models.CharField(max_length=255)),
                ('type_session', models.CharField(max_length=255)),
                ('date_d', models.DateField(default='2024-01-01')),
                ('date_f', models.DateField(default='2024-01-02')),
                ('current_affectation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
